#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 12 11:25:25 2017

@author: ceciliaLee
"""

from bs4 import BeautifulSoup  
import urllib
import urllib2
import re


url = 'https://www.londondrum.com/cityguide/west-end-theatres.php'
user_agent = 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)'
headers = { 'User-Agent' : user_agent }

try:
    request = urllib2.Request(url,headers = headers)
    response = urllib2.urlopen(request)
   # print response.read()
    
    content = response.read().decode('utf-8')
   # print content
  #  pattern = re.compile('<div.*?class="author.*?>.*?<a.*?</a>.*?<a.*?>(.*?)</a>.*?<div.*?class'+
  #                   '="content".*?title="(.*?)">(.*?)</div>(.*?)<div class="stats.*?class="number">(.*?)</i>',re.S)
    pattern = re.compile('<a.*?href="https://www.londondrum.com/cityguide/.*?>(.*?)</a>', re.S)
    # patern = re.compile(href=re.compile("elsie"), id='link1')
    items = re.findall(pattern,content)
    for i in items:
        print i+'\n'

            
  

    


except urllib2.URLError, e:
    if hasattr(e,"code"):
        print e.code
    if hasattr(e,"reason"):
        print e.reason  
        

   